theme: jekyll-theme-architect
title: Building The Social Web With The Social Web
description : This is the github page for the Computing Everywhere one-time workshop at Northwestern University designed to teach students 
to program by contributing to open source projects.
